### ISSUE TITLE
Not able to getAll()

### ISSUE THREAD

**Issue by jstein155** [douglasfinlay/node-eos-console#1]
Not able to eos.macros.getAll() (or any getAll()). undefined is returned. I'm running EOS 3.2.8.18

**Comment by jstein155** [comment]
Figured out the problem. The repository is not up to date with the modules on npm.

**Comment by douglasfinlay** [comment]
The `main` branch of this repository is ahead of the version published on NPM. If you installed this library from NPM, then you'll need to refer to that particular version's readme instead of the latest one here.
